site_name: Chris's Portfolio
site_description: Portfolio of Yi-Chun(Chris) Chang
site_author: Chris Chang
site_url: https://tpchris1.github.io/portfolio/site/index.html

theme: 
    name: material 
    language: zh-TW
    palette:
          scheme: default
          primary: blue grey
          accent: teal
    # features:
        # - navigation.sections
        # - toc.integrate
        # - navigation.instant 
        # - tabs

plugins:
    - search
    # - drawio-exporter:
    #     drawio_executable: 'D:\Program_Files\draw.io\draw.io.exe'
    # - mermaid2

markdown_extensions:
    - pymdownx.details
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    - admonition
    - attr_list
    - meta

# extra_javascript:
    # - https://unpkg.com/mermaid/dist/mermaid.min.js

nav: 
- 'Home' : 'index.md'
- 'FROZEN' : 'frozen/frozen.md' 
- 'NSFW Detection' : 'nsfw_detection/nsfw_detection.md' 
- The Tank Series:
    -  'Gen2 - Arduino-based'  : 'the_tank/the_tank_arduino.md'
    -  'Gen1 - FPGA-based'  : 'the_tank/the_tank_fpga.md' 
- 'Modeling user willingness of data contribution in online social networks' : 'modeling_user_willingness/modeling_user_willingness.md' 
- 'Gender Differences on StackOverflow' : 'gender_differences_on_stackoverflow/gender_differences_on_stackoverflow.md' 
- 'The Haunted Village' : 'the_haunted_village/the_haunted_village.md'
- 'deepeye_pack' : 'deepeye_pack/deepeye_pack.md' 