site_name: Chris's Portfolio
site_description: Portfolio of Yi-Chun(Chris) Chang
site_author: Chris Chang
site_url:  

theme: 
    name: material 
    language: zh-TW
    palette:
          scheme: default
          primary: blue grey
          accent: teal
    # features:
        # - navigation.sections
        # - toc.integrate
        # - navigation.instant 
        # - tabs

plugins:
    - search
    # - drawio-exporter:
    #     drawio_executable: 'D:\Program_Files\draw.io\draw.io.exe'
    # - mermaid2

markdown_extensions:
    - pymdownx.details
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    - admonition
    - attr_list
    - meta

extra_javascript:
    # - https://unpkg.com/mermaid/dist/mermaid.min.js

# nav:
# - '配置XE8 C++ Builder環境':
#     - 'Focus 在XE8下如何設置環境並運行' : 'XE8_env_setup/Focus_env_setup_under_XE8.md'
# - '系統架構':
#     - [基礎系統架構與名詞解釋](sys_archi/sys_archi.md)
#     - [範例code解釋](sys_archi/test_program_sample_analysis.md)
# 4. 參考文檔
#     - [G5000 Application Manual](reference/G5000%20Application%20Manual.pdf)
#     - [G5000 Users Guide](reference/G5000_Users_Guide.pdf)
#     - [FOCUS help html manual](reference/Focus_help_manual/index.htm)
#     - [74hc373 datasheet](reference/cd54hc373.pdf)
# 5. 其他文檔
#     - [Bob Focus Study ppt](other_files/Focus%20Study20190224.ppt)
#     - [UML_for_XE8_User_Guide](other_files/UML_learning/UML_user_guide/UML_for_XE8_User_Guide.md)
# 6. [Q&A匯總](q&a/q&a_all.md)